version: "0.1"

services:
  server:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: "crm_ml_server"
    ports:
      - "8080:8000"
    volumes:
        - .:/code
    env_file:
      - .env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]