version: "0.1"


services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
  tg-bot:
    build:
      context: ./client-bot
      dockerfile: Dockerfile
    container_name: tg-bot
    env_file:
      - ./client-bot/.env
    volumes:
      - ./client-bot/database:/code/database
    command: ["python", "main.py"]
    restart: unless-stopped
  ml-service:
    build:
      context: ./ml
      dockerfile: Dockerfile
    container_name: ml-service
    ports:
      - "5000:8000"
    env_file:
      - ./ml/.env
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    container_name: frontend
#    ports:
#      - "80:8000"
#    env_file:
#      - ./frontend/.env
#    restart: unless-stopped
#    command: []