from .agreement import AgreementUpdate, AgreementCreate, AgreementResponse
from .attachment import AttachmentUpdate, AttachmentCreate, AttachmentResponse
from .authorization import AuthorizationUpdate, AuthorizationCreate, AuthorizationResponse
from .bot_authorization import BotAuthorizationCreate, BotAuthorizationUpdate, BotAuthorizationResponse
from .client_agreement import ClientAgreementUpdate, ClientAgreementCreate, ClientAgreementResponse
from .client_employee import ClientEmployeeUpdate, ClientEmployeeCreate, ClientEmployeeResponse
from .client_object import ClientObjectUpdate, ClientObjectCreate, ClientObjectResponse
from .client_payment_status import ClientPaymentStatusUpdate, ClientPaymentStatusCreate, ClientPaymentStatusResponse
from .client import ClientUpdate, ClientCreate, ClientResponse
from .client_type import ClientTypeUpdate, ClientTypeCreate, ClientTypeResponse
from .device_operation_in import DeviceOperationInUpdate, DeviceOperationInCreate, DeviceOperationInResponse
from .device_operation_out import DeviceOperationOutUpdate, DeviceOperationOutCreate, DeviceOperationOutResponse
from .device_operation_move import DeviceOperationMoveUpdate, DeviceOperationMoveCreate, DeviceOperationMoveResponse
from .device import DeviceUpdate, DeviceCreate, DeviceResponse
from .employee import EmployeeUpdate, EmployeeCreate, EmployeeResponse
from .group import GroupUpdate, GroupCreate, GroupResponse
from .instruction_attachment import InstructionAttachmentUpdate, InstructionAttachmentCreate, InstructionAttachmentResponse
from .instruction import InstructionUpdate, InstructionCreate, InstructionResponse
from .observer import ObserverUpdate, ObserverCreate, ObserverResponse
from .position import PositionUpdate, PositionCreate, PositionResponse
from .service import ServiceUpdate, ServiceCreate, ServiceResponse
from .service_to_ticket import ServiceToTicketUpdate, ServiceToTicketCreate, ServiceToTicketResponse
from .sla import SLAUpdate, SLACreate, SLAResponse
from .ticket_task import TicketTaskUpdate, TicketTaskCreate, TicketTaskResponse
from .ticket import TicketUpdate, TicketCreate, TicketResponse
from .ticket_task_status import TicketTaskStatusUpdate, TicketTaskStatusCreate, TicketTaskStatusResponse
from .tmc_operation_in import TMCOperationInUpdate, TMCOperationInCreate, TMCOperationInResponse
from .tmc_operation_out import TMCOperationOutUpdate, TMCOperationOutCreate, TMCOperationOutResponse
from .tmc_operation_move import TMCOperationMoveUpdate, TMCOperationMoveCreate, TMCOperationMoveResponse
from .tmc import TMCUpdate, TMCCreate, TMCResponse
from .warehouse import WarehouseUpdate, WarehouseCreate, WarehouseResponse

