version: "0.1"

services:
  postgres:
    image: "postgres:15"
    container_name: "crm_postgres"
    shm_size: "128mb"
    user: "postgres"
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
      - "-c"
      - 'max_connections=100'
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: "10s"
      timeout: "2s"
      retries: 3
      start_period: "15s"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "pgdata:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432/tcp"
    logging: &logging
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: "unless-stopped"
    env_file:
      - .env

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8090:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9093
    networks:
      - kafka-net

  kafka:
    image: obsidiandynamics/kafka
    container_name: kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "29092:29092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:9093,EXTERNAL://:29092"
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://${SERVER_IP}:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
      CONNECT_TOPIC_CREATION_ENABLE: "true"
    healthcheck:
      test: nc -z localhost 9093 || exit
      interval: 10s
      timeout: 5s
      retries: 15
    networks:
      - kafka-net
    env_file:
      - .env

networks:
  kafka-net:

volumes:
  pgdata: